development:
  adapter: mysql
  database: cookbook
  host: localhost
  username: root
  password:

test:
  adapter: mysql
  database: cookbook
  host: localhost
  username: root
  password:

production:
  adapter: mysql
  database: cookbook
  host: localhost
  username: root
  password:
